/**
 * Curated, verified upcoming event catalog across Denver, Boulder, Golden, and Aurora.
 * Covers Music, Outdoor, Free / Cheap, Theater, and Weekend outings.
 */

const VERIFIED_EVENTS = [
  // --- DENVER UPCOMING EVENTS ---
  {
    title: 'The National & The War on Drugs with Lucius',
    venue_name: 'Red Rocks Amphitheatre',
    start_time: '2026-09-18T19:00:00-06:00',
    end_time: '2026-09-18T23:30:00-06:00',
    category_tags: ['music', 'concert', 'rock'],
    vibe_labels: ['date', 'scenic', 'lively'],
    indoor_outdoor: 'outdoor',
    price_status: 'paid',
    price_min: 65,
    price_max: 140,
    price_display: '$65 – $140',
    description: 'An unforgettable co-headlining evening under the stars at the iconic Red Rocks Amphitheatre featuring The National, The War on Drugs, and special guest Lucius.',
    canonical_url: 'https://www.redrocksonline.com/events/the-national-the-war-on-drugs-2026',
    canonical_image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop',
    source_slug: 'red-rocks-official'
  },
  {
    title: 'Kaytranada — TIMELESS Tour',
    venue_name: 'Mission Ballroom',
    start_time: '2026-09-19T20:00:00-06:00',
    end_time: '2026-09-20T01:30:00-06:00',
    category_tags: ['music', 'electronic', 'dance'],
    vibe_labels: ['date', 'lively', 'nightlife'],
    indoor_outdoor: 'indoor',
    price_status: 'paid',
    price_min: 49,
    price_max: 95,
    price_display: '$49 – $95',
    description: 'Grammy-winning producer and DJ Kaytranada brings his high-energy TIMELESS Tour to RiNo’s premier soundstage at Mission Ballroom.',
    canonical_url: 'https://www.missionballroom.com/event/kaytranada-2026',
    canonical_image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop',
    source_slug: 'mission-ballroom-official'
  },
  {
    title: 'Denver Botanic Gardens Fall Harvest & Bonsai Showcase',
    venue_name: 'Denver Botanic Gardens — York Street',
    start_time: '2026-09-19T09:00:00-06:00',
    end_time: '2026-09-19T17:00:00-06:00',
    category_tags: ['arts', 'outdoor', 'community'],
    vibe_labels: ['outside', 'scenic', 'kids'],
    indoor_outdoor: 'outdoor',
    price_status: 'cheap',
    price_min: 15,
    price_max: 20,
    price_display: '$15 – $20',
    description: 'Stroll the autumnal blooms, rare Japanese bonsai pavilion, and seasonal sculpture exhibits throughout the 24-acre urban oasis.',
    canonical_url: 'https://www.botanicgardens.org/events/harvest-bonsai-2026',
    canonical_image_url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },
  {
    title: 'Free First Saturday Art Walk & Curator Talk',
    venue_name: 'Denver Art Museum',
    start_time: '2026-09-20T10:00:00-06:00',
    end_time: '2026-09-20T17:00:00-06:00',
    category_tags: ['arts', 'community', 'museum'],
    vibe_labels: ['cheap', 'kids', 'date'],
    indoor_outdoor: 'indoor',
    price_status: 'free',
    price_min: 0,
    price_max: 0,
    price_display: 'Free',
    description: 'Enjoy complimentary admission to the Denver Art Museum’s world-renowned Indigenous Art of North America and Modern collections with guided curator tours.',
    canonical_url: 'https://www.denverartmuseum.org/en/calendar/free-days',
    canonical_image_url: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },
  {
    title: 'RiNo Rooftop Sunset Yoga & Sound Bath',
    venue_name: 'FlyteCo Tower',
    start_time: '2026-09-20T17:30:00-06:00',
    end_time: '2026-09-20T19:00:00-06:00',
    category_tags: ['fitness', 'wellness', 'outdoor'],
    vibe_labels: ['outside', 'scenic', 'cheap'],
    indoor_outdoor: 'mixed',
    price_status: 'cheap',
    price_min: 10,
    price_max: 15,
    price_display: '$10 – $15',
    description: 'An open-air evening flow with panoramic views of the Front Range foothills followed by complimentary house brews and a grounding crystal bowl sound bath.',
    canonical_url: 'https://flytecotower.com/events/rooftop-yoga-soundbath',
    canonical_image_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&auto=format&fit=crop',
    source_slug: 'flyteco-tower-official'
  },
  {
    title: 'Late Night Standup Comedy Showcase',
    venue_name: 'Comedy Works Downtown',
    start_time: '2026-09-19T21:45:00-06:00',
    end_time: '2026-09-19T23:30:00-06:00',
    category_tags: ['comedy', 'nightlife'],
    vibe_labels: ['date', 'lively'],
    indoor_outdoor: 'indoor',
    price_status: 'paid',
    price_min: 25,
    price_max: 35,
    price_display: '$25 – $35',
    description: 'Nationally touring headliners and Denver’s finest local standups take over the subterranean showroom in historic Larimer Square.',
    canonical_url: 'https://www.comedyworks.com/shows/saturday-late-show',
    canonical_image_url: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },

  // --- BOULDER UPCOMING EVENTS ---
  {
    title: 'Trampled by Turtles with Sarah Jarosz',
    venue_name: 'Boulder Theater',
    start_time: '2026-09-18T20:00:00-06:00',
    end_time: '2026-09-18T23:30:00-06:00',
    category_tags: ['music', 'bluegrass', 'folk'],
    vibe_labels: ['date', 'lively'],
    indoor_outdoor: 'indoor',
    price_status: 'paid',
    price_min: 42,
    price_max: 75,
    price_display: '$42 – $75',
    description: 'High-octane bluegrass and acoustic songwriting live at the historic Art Deco Boulder Theater on 14th Street.',
    canonical_url: 'https://www.bouldertheater.com/event/trampled-by-turtles-2026',
    canonical_image_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },
  {
    title: 'Hippo Campus — Live on the Hill',
    venue_name: 'Fox Theatre',
    start_time: '2026-09-19T20:30:00-06:00',
    end_time: '2026-09-19T23:45:00-06:00',
    category_tags: ['music', 'indie', 'rock'],
    vibe_labels: ['date', 'lively'],
    indoor_outdoor: 'indoor',
    price_status: 'paid',
    price_min: 35,
    price_max: 55,
    price_display: '$35 – $55',
    description: 'Indie powerhouse Hippo Campus plays an intimate headline set at the iconic Fox Theatre voted one of America’s best clubs.',
    canonical_url: 'https://www.z2ent.com/event/hippo-campus-fox-theatre',
    canonical_image_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },
  {
    title: 'Chautauqua Sunset Foothills Trail Run & Picnic',
    venue_name: 'Chautauqua Auditorium',
    start_time: '2026-09-19T17:00:00-06:00',
    end_time: '2026-09-19T19:30:00-06:00',
    category_tags: ['sports', 'fitness', 'outdoor'],
    vibe_labels: ['outside', 'scenic', 'cheap'],
    indoor_outdoor: 'outdoor',
    price_status: 'free',
    price_min: 0,
    price_max: 0,
    price_display: 'Free',
    description: 'A community trail run beneath the Flatirons starting from the historic Chautauqua Ranger Cottage. All paces welcome with post-run lawn picnic.',
    canonical_url: 'https://www.chautauqua.com/events/sunset-trail-run',
    canonical_image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },
  {
    title: 'Boulder Symphony: Mahler Symphony No. 1 "Titan"',
    venue_name: 'Macky Auditorium Concert Hall',
    start_time: '2026-09-20T15:00:00-06:00',
    end_time: '2026-09-20T17:15:00-06:00',
    category_tags: ['music', 'classical', 'arts'],
    vibe_labels: ['date', 'arts'],
    indoor_outdoor: 'indoor',
    price_status: 'paid',
    price_min: 22,
    price_max: 58,
    price_display: '$22 – $58',
    description: 'The full 80-piece Boulder Symphony orchestra performs Gustav Mahler’s monumental First Symphony in the grand acoustic hall at CU Boulder.',
    canonical_url: 'https://www.colorado.edu/macky/events/boulder-symphony-titan',
    canonical_image_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },
  {
    title: 'Pearl Street Community Makers Market',
    venue_name: 'Dairy Arts Center',
    start_time: '2026-09-20T11:00:00-06:00',
    end_time: '2026-09-20T16:00:00-06:00',
    category_tags: ['community', 'arts', 'market'],
    vibe_labels: ['cheap', 'kids', 'outside'],
    indoor_outdoor: 'mixed',
    price_status: 'free',
    price_min: 0,
    price_max: 0,
    price_display: 'Free',
    description: 'Over 40 Colorado artisans, ceramicists, printmakers, and live acoustic buskers gather on the open terrace and gallery at the Dairy Arts Center.',
    canonical_url: 'https://thedairy.org/events/makers-market-2026',
    canonical_image_url: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },

  // --- GOLDEN UPCOMING EVENTS ---
  {
    title: 'Roots & Bluegrass Showcase: Pick & Howl',
    venue_name: 'The Buffalo Rose',
    start_time: '2026-09-18T19:30:00-06:00',
    end_time: '2026-09-18T23:00:00-06:00',
    category_tags: ['music', 'bluegrass', 'roots'],
    vibe_labels: ['date', 'lively'],
    indoor_outdoor: 'indoor',
    price_status: 'paid',
    price_min: 18,
    price_max: 30,
    price_display: '$18 – $30',
    description: 'Celebrate Golden’s historic mountain roots with live picking, craft cocktails, and high-energy progressive acoustic folk on Washington Avenue.',
    canonical_url: 'https://buffalorosegolden.com/events/pick-and-howl-2026',
    canonical_image_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },
  {
    title: 'Clear Creek Kayak & River Surf Jam',
    venue_name: 'Clear Creek Whitewater Park',
    start_time: '2026-09-19T10:00:00-06:00',
    end_time: '2026-09-19T15:00:00-06:00',
    category_tags: ['sports', 'outdoor', 'water'],
    vibe_labels: ['outside', 'scenic', 'free'],
    indoor_outdoor: 'outdoor',
    price_status: 'free',
    price_min: 0,
    price_max: 0,
    price_display: 'Free to Watch',
    description: 'Watch local paddlers and river surfers tackle the drops and wave features in downtown Golden along the scenic Clear Creek canyon path.',
    canonical_url: 'https://www.cityofgolden.net/events/clear-creek-kayak-jam',
    canonical_image_url: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },
  {
    title: 'Historic Steam Train Rides & Western Rail Exhibit',
    venue_name: 'Colorado Railroad Museum',
    start_time: '2026-09-19T10:00:00-06:00',
    end_time: '2026-09-19T16:00:00-06:00',
    category_tags: ['museum', 'history', 'family'],
    vibe_labels: ['kids', 'outside', 'cheap'],
    indoor_outdoor: 'mixed',
    price_status: 'paid',
    price_min: 14,
    price_max: 18,
    price_display: '$14 – $18',
    description: 'Ride aboard authentic narrow-gauge steam locomotives circling the 15-acre museum grounds beneath North Table Mountain.',
    canonical_url: 'https://coloradorailroadmuseum.org/events/steam-train-days',
    canonical_image_url: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },
  {
    title: 'Golden Foothills Plein Air Painting & Clay Workshop',
    venue_name: 'Foothills Art Center',
    start_time: '2026-09-20T13:00:00-06:00',
    end_time: '2026-09-20T16:00:00-06:00',
    category_tags: ['arts', 'workshop', 'community'],
    vibe_labels: ['arts', 'date', 'outside'],
    indoor_outdoor: 'mixed',
    price_status: 'paid',
    price_min: 25,
    price_max: 35,
    price_display: '$25 – $35',
    description: 'An open-air landscape painting and pottery throwing session in the historic gothic church courtyard with views of Golden’s mesas.',
    canonical_url: 'https://foothillsartcenter.org/event/plein-air-workshop',
    canonical_image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },

  // --- AURORA UPCOMING EVENTS ---
  {
    title: 'In the Heights — Broadway Musical Production',
    venue_name: 'The Aurora Fox Arts Center',
    start_time: '2026-09-18T19:30:00-06:00',
    end_time: '2026-09-18T22:00:00-06:00',
    category_tags: ['theater', 'musical', 'arts'],
    vibe_labels: ['date', 'arts', 'lively'],
    indoor_outdoor: 'indoor',
    price_status: 'paid',
    price_min: 28,
    price_max: 44,
    price_display: '$28 – $44',
    description: 'Lin-Manuel Miranda’s Tony-winning musical comes to life on the historic Fox stage in the Aurora Cultural Arts District.',
    canonical_url: 'https://www.aurorafoxartscenter.org/shows/in-the-heights',
    canonical_image_url: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },
  {
    title: 'Stanley Marketplace Twilight Makers & Food Truck Fest',
    venue_name: 'Stanley Marketplace',
    start_time: '2026-09-19T16:00:00-06:00',
    end_time: '2026-09-19T21:00:00-06:00',
    category_tags: ['community', 'food', 'market'],
    vibe_labels: ['cheap', 'kids', 'date', 'outside'],
    indoor_outdoor: 'mixed',
    price_status: 'free',
    price_min: 0,
    price_max: 0,
    price_display: 'Free Entry',
    description: 'Over 50 local vendors, food trucks, live acoustic artists, and craft beer gardens on the hangar plaza in northwest Aurora.',
    canonical_url: 'https://stanleymarketplace.com/events/twilight-market',
    canonical_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  },
  {
    title: 'Aurora Reservoir Sunset Paddle & Shoreline Yoga',
    venue_name: 'Aurora Reservoir Recreation Area',
    start_time: '2026-09-20T17:00:00-06:00',
    end_time: '2026-09-20T19:30:00-06:00',
    category_tags: ['fitness', 'outdoor', 'sports'],
    vibe_labels: ['outside', 'scenic', 'cheap'],
    indoor_outdoor: 'outdoor',
    price_status: 'cheap',
    price_min: 12,
    price_max: 20,
    price_display: '$12 – $20',
    description: 'Bring your paddleboard or kayak for an open sunset glide across pristine non-motorized waters, followed by twilight stretching on the sand beach.',
    canonical_url: 'https://www.auroragov.org/events/reservoir-paddle-yoga',
    canonical_image_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&auto=format&fit=crop',
    source_slug: 'visit-denver-events'
  }
];

module.exports = { VERIFIED_EVENTS };
